kind: pipeline
name: default

steps:
  - name: wisdom-service
    image: plugins/docker
    settings:
      repo: mejlholm/wisdom-service
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
      dockerfile: wisdom-service/Dockerfile
      context: wisdom-service

  - name: wisdom-frontend
    image: plugins/docker
    settings:
      repo: mejlholm/wisdom-frontend
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
      dockerfile: wisdom-frontend/Dockerfile
      context: wisdom-frontend

  - name: bump-versions
    image: git
    commands:
      - version=$(git rev-parse HEAD)
      - sed -i -E "s,image: mejlholm/wisdom-service:(.*)$,image: mejlholm/wisdom-service:$version,g" wisdom-service/deploy/wisdom-service-deployment.yaml
      - sed -i -E "s,image: mejlholm/wisdom-frontend:(.*)$,image: mejlholm/wisdom-frontend:$version,g" wisdom-service/deploy/wisdom-service-deployment.yaml

      - git add wisdom-service/deploy/wisdom-service-deployment.yaml
      - git add wisdom-frontend/deploy/wisdom-frontend-deployment.yaml
      - git commit -m "Drone bumped image tags automatically"
      - git push origin master
