kind: pipeline
name: default

steps:
  - name: build-wisdom-service
    image: plugins/docker
    settings:
      repo: mejlholm/wisdom-service
      auto_tag: true
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
      dockerfile: wisdom-service/Dockerfile
      context: wisdom-service

  - name: build-wisdom-frontend
    image: plugins/docker
    settings:
      repo: mejlholm/wisdom-frontend
      tags:
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
      dockerfile: wisdom-frontend/Dockerfile
      context: wisdom-frontend

  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
    depends_on:
      - build-wisdom-service
      - build-wisdom-frontend

trigger:
  event:
    exclude:
    - tag