kind: pipeline
name: default

steps:
  - name: update-yaml-versions
    image: docker:git
    commands:
      - git config --global user.name "mejlholm"
      - >
        sed -i -E "s,image: mejlholm/wisdom-service:(.*)$,image: mejlholm/wisdom-service:"$(git rev-parse HEAD)",g" wisdom-service/deploy/wisdom-service-deployment.yaml
      - git add wisdom-service/deploy/wisdom-service-deployment.yaml
      - >
        sed -i -E "s,image: mejlholm/wisdom-frontend:(.*)$,image: mejlholm/wisdom-frontend:"$(git rev-parse HEAD)",g" wisdom-frontend/deploy/wisdom-frontend-deployment.yaml
      - git add wisdom-service/deploy/wisdom-service-deployment.yaml
      - git commit -m "Bumped version"
      - git push origin master

  - name: build-wisdom-service
    image: plugins/docker
    settings:
      repo: mejlholm/wisdom-service
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
      dockerfile: wisdom-service/Dockerfile
      context: wisdom-service

  - name: build-wisdom-frontend
    image: plugins/docker
    settings:
      repo: mejlholm/wisdom-frontend
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_password
      dockerfile: wisdom-frontend/Dockerfile
      context: wisdom-frontend
