---
kind: Service
apiVersion: v1
metadata:
  name: wisdom-service
  namespace: apps
spec:
  selector:
    app: wisdon-service-deployment
  ports:
    - name: default
      port: 8081
      protocol: TCP
      targetPort: 8081
